import React, { createContext, useState, useContext, useEffect } from 'react'

const translations = {
  bm: {
    // ========== COMMON / NAVIGATION ==========
    'dashboard': 'Papan Pemuka',
    'pos': 'POS',
    'kitchen': 'Dapur',
    'manage_menu': 'Urus Menu',
    'manage_categories': 'Urus Kategori',
    'manage_staff': 'Urus Kakitangan',
    'manage_tables': 'Urus Meja',
    'table_qrs': 'QR Meja',
    'system_settings': 'Tetapan Sistem',
    'reports': 'Laporan',
    'light_mode': 'Mod Terang',
    'dark_mode': 'Mod Gelap',
    'logout': 'Log Keluar',
    'english': 'English',
    'bahasa': 'Bahasa',
    
    // ========== LOGIN PAGE ==========
    'welcome_back': 'Selamat Datang Kembali!',
    'sign_in_continue': 'Sila log masuk untuk teruskan',
    'username': 'Nama Pengguna',
    'password': 'Kata Laluan',
    'login': 'Log Masuk',
    'logging_in': 'Sedang Log Masuk...',
    'login_title': 'Sistem POS untuk Restoran Kecil & Sederhana',
    'enter_username': 'Masukkan nama pengguna',
    'enter_password': 'Masukkan kata laluan',
    'username_password_required': 'Nama pengguna dan kata laluan diperlukan',
    'invalid_credentials': 'Nama pengguna atau kata laluan salah',
    'welcome': 'Selamat datang',
    'login_error': 'Ralat log masuk',
    'demo_credentials': 'Kredensial Demo',
    'login_footer': 'Sistem POS Restoran',
    'password_min_length': 'Kata laluan perlulah sekurang-kurangnya 6 aksara',
    'password_optional': 'Kata laluan (biarkan kosong jika tidak mahu tukar)',
    'password_required': 'Kata laluan diperlukan',
    'confirm_password': 'Sahkan kata laluan',
    'new_password': 'Kata laluan baru',
    'confirm_new_password': 'Sahkan kata laluan baru',
    'not_match': 'tidak sepadan',
    'already_exists': 'sudah wujud',
    'required': 'diperlukan',
    'confirm_delete': 'Anda pasti mahu padam',
    'error_updating': 'Ralat semasa mengemaskini',
    'no_orders_to_complete': 'Tiada pesanan untuk diselesaikan',
    'confirm_complete_all': 'Selesaikan semua {count} pesanan?',
    'orders_completed': 'pesanan diselesaikan',
    'complete_all': 'Selesaikan Semua',
    
    // ========== TRACK ORDER ==========
    'track_order': 'Jejak Pesanan Anda',
    'enter_order_number': 'Masukkan nombor pesanan',
    'searching': 'Mencari...',
    'order_not_found': 'Pesanan tidak dijumpai',
    'order_type': 'Jenis Pesanan',
    'customer': 'Pelanggan',
    'order_items': 'Item Pesanan',
    'total': 'Jumlah',
    'estimated_time': 'Anggaran Masa Siap',
    'almost_ready': 'Hampir siap!',
    'refresh_status': 'Muat Semula Status',
    'auto_refresh': 'Muat semula automatik',
    'order': 'Pesanan',
    'at': 'pada',
    'table': 'Meja',
    'take_away': 'Bungkus',
    'dine_in': 'Makan di sini',
    'guest': 'Tetamu',
    'note': 'Nota',
    'pending': 'Menunggu',
    'preparing': 'Sedang Disiapkan',
    'ready': 'Sedia',
    'completed': 'Selesai',
    'cancelled': 'Dibatalkan',
    'received': 'Diterima',
    
    // ========== STAFF APP ==========
    'service_charge': 'Caj Perkhidmatan',
    'tax': 'Cukai',
    'unpaid': 'Belum Bayar',
    'new_order': 'Pesanan Baru',
    'cart': 'Keranjang',
    'empty_cart': 'Keranjang kosong',
    'place_order': 'Hantar Pesanan',
    'record_payment': 'Rekod Bayaran',
    'payment_method': 'Kaedah Bayaran',
    'cash': 'Tunai',
    'tng': 'Touch n Go',
    'bank': 'Pindahan Bank',
    'subtotal': 'Jumlah Kecil',
    'add': 'Tambah',
    'edit': 'Ubah',
    'delete': 'Padam',
    'save': 'Simpan',
    'cancel': 'Batal',
    'close': 'Tutup',
    'print': 'Cetak',
    'search': 'Cari',
    'staff': 'Kakitangan',
    'accept': 'Terima',
    'date': 'Tarikh',
    'id': 'ID',
    'status': 'Status',
    'history': 'Sejarah',
    'btn_save': 'Simpan',
    'activate': 'Aktifkan',
    'promotions': 'Promosi',
    'name': 'Nama',
    'price': 'Harga',
    'type': 'Jenis',
    'image': 'Gambar',
    'description': 'Keterangan',
    'in_stock': 'Ada Stok',
    
    // ========== KITCHEN APP ==========
    'kitchen_title': 'Dapur',
    'kitchen_subtitle': 'Urus Pesanan Makanan & Minuman',
    'new_orders': 'Pesanan Baru',
    'preparing_orders': 'Sedang Masak',
    'ready_orders': 'Sedia',
    'completed_orders': 'Selesai',
    'start_cooking': 'Mula Masak',
    'finish_cooking': 'Siap Masak',
    'complete': 'Selesai',
    'waiting': 'Menunggu',
    'minutes': 'min',
    'hours': 'jam',
    'just_now': 'Baru sahaja',
    'food_kitchen': 'Makanan',
    'drink_kitchen': 'Minuman',
    'no_food_orders': 'Tiada Pesanan Makanan',
    'no_drink_orders': 'Tiada Pesanan Minuman',
    'no_preparing_orders': 'Tiada Pesanan Sedang Dimasak',
    'no_ready_orders': 'Tiada Pesanan Sedia',
    'no_completed_orders': 'Tiada Pesanan Selesai',
    'search_orders': 'Cari pesanan...',
    'sound': 'Bunyi',
    'refresh': 'Segar Semula',
    'process_immediately': 'Sila proses segera',
    
    // ========== MANAGE STAFF ==========
    'add_staff': 'Tambah Kakitangan',
    'reset_password': 'Reset Kata Laluan',
    'kitchen_staff': 'Dapur',
    'admin': 'Pentadbir',
    'full_name': 'Nama Penuh',
    'pos_access': 'Akses POS',
    'kitchen_access': 'Akses Dapur',
    'full_access': 'Akses Penuh',
    'cannot_delete_admin': 'Tidak boleh padam admin',
    'cannot_delete_self': 'Tidak boleh padam diri sendiri',
    'staff_added': 'Kakitangan berjaya ditambah',
    'staff_updated': 'Kakitangan berjaya dikemaskini',
    'staff_deleted': 'Kakitangan berjaya dipadam',
    'password_reset_success': 'Kata laluan berjaya direset',
    'manage_staff_desc': 'Urus kakitangan dan akses sistem restoran anda',
    'search_staff': 'Cari kakitangan...',
    'staff_found': 'kakitangan dijumpai',
    'no_staff': 'Tiada kakitangan',
    'edit_staff': 'Edit Kakitangan',
    'min_6_chars': 'min 6 aksara',
    'cannot_change_role': 'Tidak boleh menukar peranan sendiri',
    'reset': 'Reset',
    'access': 'Akses',
    'both_access': 'POS & Dapur',
    'pos_only': 'POS Sahaja',
    'kitchen_only': 'Dapur Sahaja',
    'full_access_role': 'Akses Penuh',
    'stats_total_staff': 'Jumlah Kakitangan',
    'stats_admin': 'Pentadbir',
    'stats_kitchen_access': 'Akses Dapur',
    'stats_pos_staff': 'Staf POS',
    
    // ========== MANAGE MENU ==========
    'regular_menu': 'Menu Biasa',
    'special_menu': 'Menu Istimewa',
    'add_regular_menu': 'Tambah Menu Biasa',
    'add_drink': 'Tambah Minuman',
    'select_category': 'Pilih Kategori',
    'uploading': 'Sedang muat naik...',
    'stock': 'Stok',
    'low_stock_alert': 'Amaran Stok Rendah',
    'out_of_stock': 'Habis Stok',
    'left': 'lagi',
    
    // ========== MANAGE CATEGORIES ==========
    'manage_categories_desc': 'Urus kategori menu untuk restoran anda',
    'search_categories': 'Cari kategori...',
    'category_name_required': 'Nama kategori diperlukan',
    'category_added': 'Kategori berjaya ditambah',
    'category_updated': 'Kategori berjaya dikemaskini',
    'category_deleted': 'Kategori berjaya dipadam',
    'edit_category': 'Edit Kategori',
    'category_not_found': 'Kategori tidak dijumpai',
    'confirm_delete_category': 'Anda pasti mahu padam kategori',
    'add_category': 'Tambah Kategori',
    'category_name': 'Nama Kategori',
    'select_icon': 'Pilih Ikon',
    'or_type': 'Atau taip',
    'sort_order': 'Susunan',
    'sort_order_desc': 'Nombor kecil akan dipaparkan dahulu',
    'cannot_delete': 'Tidak boleh padam',
    'has_items': 'mempunyai',
    'menu_items': 'item menu',
    'change_category_first': 'Tukar kategori item dahulu',
    
    // ========== MANAGE TABLES ==========
    'manage_tables_desc': 'Tambah, edit atau padam meja restoran',
    'add_table': 'Tambah Meja',
    'edit_capacity': 'Edit Kapasiti',
    'capacity_people': 'orang',
    'capacity_question': 'Berapa ramai pelanggan yang boleh duduk di meja ini?',
    'table_exists': 'sudah wujud',
    'table_has_unpaid_orders': 'mempunyai pesanan belum selesai. Sila selesaikan dahulu.',
    'table_added': 'berjaya ditambah',
    'table_updated': 'dikemaskini',
    'table_deleted': 'berjaya dipadam',
    'status_available': 'Tersedia',
    'status_occupied': 'Diduduki',
    'status_reserved': 'Ditempah',
    'status_inactive': 'Tidak Aktif',
    'no_tables': 'Tiada meja. Klik "Tambah Meja" untuk mula.',
    'edit_capacity_for': 'Edit Kapasiti Meja',
    'select_status': 'Pilih Status',
    
    // ========== MANAGE SETTINGS ==========
    'restaurant_logo': 'Logo Restoran',
    'select_logo': 'Pilih Logo',
    'upload_failed': 'Gagal muat naik',
    'logo_uploaded': 'Logo berjaya dimuat naik',
    'logo_deleted': 'Logo berjaya dipadam',
    'delete_image': 'Padam gambar?',
    'save_error': 'Gagal menyimpan',
    'settings_saved': 'Tetapan disimpan',
    'enable_special_menu': 'Aktifkan Menu Istimewa',
    'special_menu_title': 'Tajuk Menu Istimewa',
    'business_hours': 'Waktu Operasi',
    'start': 'Mula',
    'end': 'Tamat',
    'printer_type': 'Jenis Pencetak',
    'thermal_printer': 'Pencetak Thermal',
    'a4_printer': 'Pencetak A4',
    'no_printer': 'Tiada Pencetak',
    'auto_print': 'Cetak Auto',
    'notification_sound': 'Bunyi Notifikasi',
    'kitchen_app': 'Aplikasi Dapur',
    'kitchen_on_off': 'Hidup/Matikan mod dapur digital',
    'kitchen_disabled': 'Dapur Dimatikan',
    'kitchen_disabled_desc': 'Dapur sedang dimatikan. Pesanan akan terus ke kaunter.',
    'go_to_settings': 'Pergi ke Tetapan',
    'language': 'Bahasa',
    'saving': 'Menyimpan...',
    'restaurant_name': 'Nama Restoran',
    'preview': 'Pratonton',
    'example': 'contoh',
    'login_page': 'Halaman Login',
    'welcome_text': 'Teks Selamat Datang',
    'subtitle_text': 'Teks Subtitle',
    'branding_text': 'Teks Jenama',
    'footer_text': 'Teks Footer',
    'auto_complete': 'Auto Lengkap',
    'minutes_to_complete': 'Minut untuk Auto Lengkap',
    'order_will_be_completed': 'Pesanan akan dilengkapkan secara automatik selepas X minit',
    'kitchen_disabled_auto': 'Dapur Dimatikan - Auto Complete Aktif',
    
    // ========== ADMIN REPORT ==========
    'sales_report': 'Laporan Jualan',
    'sales_analysis': 'Analisis Jualan',
    'today_sales': 'Jualan Hari Ini',
    'week_sales': 'Jualan Minggu Ini',
    'month_sales': 'Jualan Bulan Ini',
    'total_sales': 'Jumlah Keseluruhan',
    'total_service_charge': 'Jumlah Caj Perkhidmatan',
    'total_tax': 'Jumlah Cukai',
    'pending_payments_warning': 'Amaran: Terdapat',
    'unpaid_orders': 'pesanan belum dibayar',
    'record_payment_staff': 'Sila rekod bayaran di halaman POS',
    'sales_trend': 'Trend Jualan',
    'last_7_days': '7 Hari Terakhir',
    'top_items': 'Item Terlaris',
    'sold': 'Terjual',
    'orders_list': 'Senarai Pesanan',
    'no_orders': 'Tiada pesanan',
    'items': 'item',
    'time': 'Masa',
    'customer_name': 'Nama Pelanggan',
    'all_orders': 'Semua Pesanan',
    'paid_status': 'Sudah Bayar',
    'unpaid_status': 'Belum Bayar',
    'showing': 'Menunjukkan',
    'of': 'daripada',
    'orders': 'pesanan',
    'export_csv': 'Eksport CSV',
    'export_excel': 'Eksport Excel',
    'export_pdf': 'Eksport PDF',
    'first': 'Pertama',
    'prev': 'Sebelum',
    'next': 'Seterusnya',
    'last': 'Terakhir',
    'chart': 'Carta',
    'last_updated': 'Kemaskini terakhir',
    'table_number': 'Nombor Meja',
    
    // ========== CUSTOMER MENU ==========
    'scan_qr': 'Imbas QR untuk pesan',
    'table_required': 'Nombor Meja Diperlukan',
    'enter_table': 'Masukkan No. Meja',
    'please_enter_table': 'Sila masukkan nombor meja untuk mula memesan',
    'order_confirmed': 'Pesanan Dikonfirmasi!',
    'order_sent_to_kitchen': 'Pesanan anda telah dihantar ke dapur',
    'order_number_label': 'Nombor Pesanan:',
    'copy': 'Salin',
    'new_order_btn': 'Pesanan Baru',
    'your_order': 'Pesanan Anda',
    'cart_empty': 'Keranjang kosong',
    'service': 'Perkhidmatan',
    'tax_label': 'Cukai',
    'total_label': 'Jumlah',
    'your_name': 'Nama anda',
    'phone_optional': 'Telefon (pilihan)',
    'special_notes': 'Catatan khas...',
    'back_to_menu': 'Kembali ke Menu',
    'please_enter_table_first': 'Sila masuk meja',
    'select_temperature': 'Pilih suhu',
    'hot': 'Panas',
    'cold': 'Sejuk',
    'add_to_cart_btn': 'Tambah ke Keranjang',
    'confirm_order_title': 'Sahkan Pesanan',
    'confirm_order_desc': 'Sila semak semula pesanan anda sebelum menghantar',
    'table_label': 'Meja:',
    'customer_label': 'Pelanggan:',
    'total_items_label': 'Jumlah Item:',
    'total_payment_label': 'Jumlah Bayaran:',
    'back_btn': 'Kembali',
    'close_btn': 'Tutup',
    'confirm_btn': 'Sahkan',
    'active_promotions': 'Promosi Giat!',
    'buy': 'Beli',
    'get': 'dapat',
    'free': 'percuma',
    'save_discount': 'Jimat',
    'only': 'Hanya',
    'added': 'Ditambah',
    'buy_promo': 'Beli Promo',
    'add_item': 'Tambah',
    'promo_badge': 'PROMO',
    'please_review': 'Sila semak semula pesanan anda',
    'order_sent': 'Pesanan Dihantar!',
    'order_sent_desc': 'Pesanan anda telah dihantar ke dapur.',
    'find_menu': 'Cari menu...',
    'menu_billing': 'Menu & Bil',
    'billing': 'Bil',
    'select_table': 'Pilih Meja',
    'find_order': 'Cari pesanan...',
    'btn_print': 'Cetak',
    'btn_pay': 'Bayar',
    'btn_receipt': 'Resit',
    'payment_received': 'Bayaran diterima',
    'thank_you': 'Terima kasih',
    'receipt_footer': 'Sila simpan resit ini untuk rujukan',
    'print_all': 'Cetak Semua',
    
    // ========== DASHBOARD ==========
    'total_orders': 'Jumlah Pesanan',
    'active_tables': 'Meja Aktif',
    'popular_items': 'Item Popular',
    'payment_breakdown': 'Pecahan Bayaran',
    'peak_hours': 'Waktu Sibuk',
    'top_categories': 'Kategori Teratas',
    'recent_orders': 'Pesanan Terkini',
    'refresh_data': 'Muat Semula Data',
    'summary': 'Ringkasan',
    'times': 'kali',
    'paid': 'Sudah Bayar',
    'tables': 'meja',
    'sales': 'jualan',
    'today': 'Hari Ini',
    'week': 'Minggu Ini',
    'month': 'Bulan Ini',
    'no_data': 'Tiada data',
    'loading': 'Sedang memuatkan...',
    'auto_refresh_notify': 'Data auto-refresh',
  },
  en: {
    // ========== COMMON / NAVIGATION ==========
    'dashboard': 'Dashboard',
    'pos': 'POS',
    'kitchen': 'Kitchen',
    'manage_menu': 'Manage Menu',
    'manage_categories': 'Manage Categories',
    'manage_staff': 'Manage Staff',
    'manage_tables': 'Manage Tables',
    'table_qrs': 'Table QR',
    'system_settings': 'System Settings',
    'reports': 'Reports',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'logout': 'Logout',
    'english': 'English',
    'bahasa': 'Bahasa',
    
    // ========== LOGIN PAGE ==========
    'welcome_back': 'Welcome Back!',
    'sign_in_continue': 'Please sign in to continue',
    'username': 'Username',
    'password': 'Password',
    'login': 'Login',
    'logging_in': 'Logging in...',
    'login_title': 'POS System for Small & Medium Restaurants',
    'enter_username': 'Enter username',
    'enter_password': 'Enter password',
    'username_password_required': 'Username and password required',
    'invalid_credentials': 'Invalid username or password',
    'welcome': 'Welcome',
    'login_error': 'Login error',
    'demo_credentials': 'Demo Credentials',
    'login_footer': 'Restaurant POS System',
    'password_min_length': 'Password must be at least 6 characters',
    'password_optional': 'Password (leave blank to keep current)',
    'password_required': 'Password required',
    'confirm_password': 'Confirm password',
    'new_password': 'New password',
    'confirm_new_password': 'Confirm new password',
    'not_match': 'do not match',
    'already_exists': 'already exists',
    'required': 'required',
    'confirm_delete': 'Are you sure you want to delete',
    'error_updating': 'Error updating',
    'no_orders_to_complete': 'No orders to complete',
    'confirm_complete_all': 'Complete all {count} orders?',
    'orders_completed': 'orders completed',
    'complete_all': 'Complete All',
    
    // ========== TRACK ORDER ==========
    'track_order': 'Track Your Order',
    'enter_order_number': 'Enter your order number',
    'searching': 'Searching...',
    'order_not_found': 'Order not found',
    'order_type': 'Order Type',
    'customer': 'Customer',
    'order_items': 'Order Items',
    'total': 'Total',
    'estimated_time': 'Estimated Ready Time',
    'almost_ready': 'Almost ready!',
    'refresh_status': 'Refresh Status',
    'auto_refresh': 'Auto-refresh status',
    'order': 'Order',
    'at': 'at',
    'table': 'Table',
    'take_away': 'Take Away',
    'dine_in': 'Dine In',
    'guest': 'Guest',
    'note': 'Note',
    'pending': 'Pending',
    'preparing': 'Preparing',
    'ready': 'Ready',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'received': 'Received',
    
    // ========== STAFF APP ==========
    'service_charge': 'Service Charge',
    'tax': 'Tax',
    'unpaid': 'Unpaid',
    'new_order': 'New Order',
    'cart': 'Cart',
    'empty_cart': 'Cart is empty',
    'place_order': 'Place Order',
    'record_payment': 'Record Payment',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'tng': 'Touch n Go',
    'bank': 'Bank Transfer',
    'subtotal': 'Subtotal',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'print': 'Print',
    'search': 'Search',
    'staff': 'Staff',
    'accept': 'Accept',
    'date': 'Date',
    'id': 'ID',
    'status': 'Status',
    'history': 'History',
    'btn_save': 'Save',
    'activate': 'Activate',
    'promotions': 'Promotions',
    'name': 'Name',
    'price': 'Price',
    'type': 'Type',
    'image': 'Image',
    'description': 'Description',
    'in_stock': 'In Stock',
    
    // ========== KITCHEN APP ==========
    'kitchen_title': 'Kitchen',
    'kitchen_subtitle': 'Manage Food & Drink Orders',
    'new_orders': 'New Orders',
    'preparing_orders': 'Preparing',
    'ready_orders': 'Ready',
    'completed_orders': 'Completed',
    'start_cooking': 'Start Cooking',
    'finish_cooking': 'Finish Cooking',
    'complete': 'Complete',
    'waiting': 'Waiting',
    'minutes': 'min',
    'hours': 'hrs',
    'just_now': 'Just now',
    'food_kitchen': 'Food',
    'drink_kitchen': 'Drinks',
    'no_food_orders': 'No Food Orders',
    'no_drink_orders': 'No Drink Orders',
    'no_preparing_orders': 'No Preparing Orders',
    'no_ready_orders': 'No Ready Orders',
    'no_completed_orders': 'No Completed Orders',
    'search_orders': 'Search orders...',
    'sound': 'Sound',
    'refresh': 'Refresh',
    'process_immediately': 'Please process immediately',
    
    // ========== MANAGE STAFF ==========
    'add_staff': 'Add Staff',
    'reset_password': 'Reset Password',
    'kitchen_staff': 'Kitchen',
    'admin': 'Admin',
    'full_name': 'Full Name',
    'pos_access': 'POS Access',
    'kitchen_access': 'Kitchen Access',
    'full_access': 'Full Access',
    'cannot_delete_admin': 'Cannot delete admin account',
    'cannot_delete_self': 'Cannot delete your own account',
    'staff_added': 'Staff added successfully',
    'staff_updated': 'Staff updated successfully',
    'staff_deleted': 'Staff deleted successfully',
    'password_reset_success': 'Password reset successfully',
    'manage_staff_desc': 'Manage staff and access for your restaurant system',
    'search_staff': 'Search staff...',
    'staff_found': 'staff found',
    'no_staff': 'No staff',
    'edit_staff': 'Edit Staff',
    'min_6_chars': 'min 6 chars',
    'cannot_change_role': 'Cannot change own role',
    'reset': 'Reset',
    'access': 'Access',
    'both_access': 'POS & Kitchen',
    'pos_only': 'POS Only',
    'kitchen_only': 'Kitchen Only',
    'full_access_role': 'Full Access',
    'stats_total_staff': 'Total Staff',
    'stats_admin': 'Admin',
    'stats_kitchen_access': 'Kitchen Access',
    'stats_pos_staff': 'POS Staff',
    
    // ========== MANAGE MENU ==========
    'regular_menu': 'Regular Menu',
    'special_menu': 'Special Menu',
    'add_regular_menu': 'Add Regular Menu',
    'add_drink': 'Add Drink',
    'select_category': 'Select Category',
    'uploading': 'Uploading...',
    'stock': 'Stock',
    'low_stock_alert': 'Low Stock Alert',
    'out_of_stock': 'Out of Stock',
    'left': 'left',
    
    // ========== MANAGE CATEGORIES ==========
    'manage_categories_desc': 'Manage menu categories for your restaurant',
    'search_categories': 'Search categories...',
    'category_name_required': 'Category name required',
    'category_added': 'Category added successfully',
    'category_updated': 'Category updated successfully',
    'category_deleted': 'Category deleted successfully',
    'edit_category': 'Edit Category',
    'category_not_found': 'Category not found',
    'confirm_delete_category': 'Are you sure you want to delete this category',
    'add_category': 'Add Category',
    'category_name': 'Category Name',
    'select_icon': 'Select Icon',
    'or_type': 'Or type',
    'sort_order': 'Sort Order',
    'sort_order_desc': 'Smaller number appears first',
    'cannot_delete': 'Cannot delete',
    'has_items': 'has',
    'menu_items': 'menu items',
    'change_category_first': 'Change category of items first',
    
    // ========== MANAGE TABLES ==========
    'manage_tables_desc': 'Add, edit or delete restaurant tables',
    'add_table': 'Add Table',
    'edit_capacity': 'Edit Capacity',
    'capacity_people': 'people',
    'capacity_question': 'How many customers can sit at this table?',
    'table_exists': 'already exists',
    'table_has_unpaid_orders': 'has unpaid orders. Please settle them first.',
    'table_added': 'added successfully',
    'table_updated': 'updated',
    'table_deleted': 'deleted successfully',
    'status_available': 'Available',
    'status_occupied': 'Occupied',
    'status_reserved': 'Reserved',
    'status_inactive': 'Inactive',
    'no_tables': 'No tables. Click "Add Table" to start.',
    'edit_capacity_for': 'Edit Table Capacity',
    'select_status': 'Select Status',
    
    // ========== MANAGE SETTINGS ==========
    'restaurant_logo': 'Restaurant Logo',
    'select_logo': 'Select Logo',
    'upload_failed': 'Upload failed',
    'logo_uploaded': 'Logo uploaded successfully',
    'logo_deleted': 'Logo deleted successfully',
    'delete_image': 'Delete image?',
    'save_error': 'Failed to save',
    'settings_saved': 'Settings saved',
    'enable_special_menu': 'Enable Special Menu',
    'special_menu_title': 'Special Menu Title',
    'business_hours': 'Business Hours',
    'start': 'Start',
    'end': 'End',
    'printer_type': 'Printer Type',
    'thermal_printer': 'Thermal Printer',
    'a4_printer': 'A4 Printer',
    'no_printer': 'No Printer',
    'auto_print': 'Auto Print',
    'notification_sound': 'Notification Sound',
    'kitchen_app': 'Kitchen App',
    'kitchen_on_off': 'Turn digital kitchen mode on/off',
    'kitchen_disabled': 'Kitchen Disabled',
    'kitchen_disabled_desc': 'Kitchen is currently disabled. Orders will go directly to counter.',
    'go_to_settings': 'Go to Settings',
    'language': 'Language',
    'saving': 'Saving...',
    'restaurant_name': 'Restaurant Name',
    'preview': 'Preview',
    'example': 'example',
    'login_page': 'Login Page',
    'welcome_text': 'Welcome Text',
    'subtitle_text': 'Subtitle Text',
    'branding_text': 'Branding Text',
    'footer_text': 'Footer Text',
    'auto_complete': 'Auto Complete',
    'minutes_to_complete': 'Minutes to Auto Complete',
    'order_will_be_completed': 'Order will be auto completed after X minutes',
    'kitchen_disabled_auto': 'Kitchen Disabled - Auto Complete Active',
    
    // ========== ADMIN REPORT ==========
    'sales_report': 'Sales Report',
    'sales_analysis': 'Sales Analysis',
    'today_sales': "Today's Sales",
    'week_sales': "This Week's Sales",
    'month_sales': "This Month's Sales",
    'total_sales': 'Total Sales',
    'total_service_charge': 'Total Service Charge',
    'total_tax': 'Total Tax',
    'pending_payments_warning': 'Warning: There are',
    'unpaid_orders': 'unpaid orders',
    'record_payment_staff': 'Please record payment in POS page',
    'sales_trend': 'Sales Trend',
    'last_7_days': 'Last 7 Days',
    'top_items': 'Top Items',
    'sold': 'Sold',
    'orders_list': 'Orders List',
    'no_orders': 'No orders',
    'items': 'items',
    'time': 'Time',
    'customer_name': 'Customer Name',
    'all_orders': 'All Orders',
    'paid_status': 'Paid',
    'unpaid_status': 'Unpaid',
    'showing': 'Showing',
    'of': 'of',
    'orders': 'orders',
    'export_csv': 'Export CSV',
    'export_excel': 'Export Excel',
    'export_pdf': 'Export PDF',
    'first': 'First',
    'prev': 'Prev',
    'next': 'Next',
    'last': 'Last',
    'chart': 'Chart',
    'last_updated': 'Last updated',
    'table_number': 'Table Number',
    
    // ========== CUSTOMER MENU ==========
    'scan_qr': 'Scan QR to order',
    'table_required': 'Table Number Required',
    'enter_table': 'Enter Table No.',
    'please_enter_table': 'Please enter your table number to start ordering',
    'order_confirmed': 'Order Confirmed!',
    'order_sent_to_kitchen': 'Your order has been sent to the kitchen',
    'order_number_label': 'Order Number:',
    'copy': 'Copy',
    'new_order_btn': 'New Order',
    'your_order': 'Your Order',
    'cart_empty': 'Cart is empty',
    'service': 'Service',
    'tax_label': 'Tax',
    'total_label': 'Total',
    'your_name': 'Your name',
    'phone_optional': 'Phone (optional)',
    'special_notes': 'Special notes...',
    'back_to_menu': 'Back to Menu',
    'please_enter_table_first': 'Please enter table number',
    'select_temperature': 'Select temperature',
    'hot': 'Hot',
    'cold': 'Cold',
    'add_to_cart_btn': 'Add to Cart',
    'confirm_order_title': 'Confirm Order',
    'confirm_order_desc': 'Please review your order before submitting',
    'table_label': 'Table:',
    'customer_label': 'Customer:',
    'total_items_label': 'Total Items:',
    'total_payment_label': 'Total Payment:',
    'back_btn': 'Back',
    'close_btn': 'Close',
    'confirm_btn': 'Confirm',
    'active_promotions': 'Active Promotions!',
    'buy': 'Buy',
    'get': 'get',
    'free': 'free',
    'save_discount': 'Save',
    'only': 'Only',
    'added': 'Added',
    'buy_promo': 'Buy Promo',
    'add_item': 'Add',
    'promo_badge': 'PROMO',
    'please_review': 'Please review your order',
    'order_sent': 'Order Sent!',
    'order_sent_desc': 'Your order has been sent to the kitchen.',
    'find_menu': 'Find menu...',
    'menu_billing': 'Menu & Billing',
    'billing': 'Billing',
    'select_table': 'Select Table',
    'find_order': 'Find order...',
    'btn_print': 'Print',
    'btn_pay': 'Pay',
    'btn_receipt': 'Receipt',
    'payment_received': 'Payment received',
    'thank_you': 'Thank you',
    'receipt_footer': 'Please keep this receipt for reference',
    'print_all': 'Print All',
    
    // ========== DASHBOARD ==========
    'total_orders': 'Total Orders',
    'active_tables': 'Active Tables',
    'popular_items': 'Popular Items',
    'payment_breakdown': 'Payment Breakdown',
    'peak_hours': 'Peak Hours',
    'top_categories': 'Top Categories',
    'recent_orders': 'Recent Orders',
    'refresh_data': 'Refresh Data',
    'summary': 'Summary',
    'times': 'times',
    'paid': 'Paid',
    'tables': 'tables',
    'sales': 'sales',
    'today': 'Today',
    'week': 'This Week',
    'month': 'This Month',
    'no_data': 'No data',
    'loading': 'Loading...',
    'auto_refresh_notify': 'Data auto-refreshed',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('kedaipos-language')
    return saved || 'bm'
  })

  useEffect(() => {
    localStorage.setItem('kedaipos-language', language)
  }, [language])

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}